# Generated by Django 5.0.6 on 2024-06-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='user_profile/Default.png', null=True, upload_to='user_profile/'),
        ),
    ]
